### ISSUE TITLE
RoadMap to sync with HomePage and PMP Project

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#114]
Q1 – 2022
Project launched with core team 
Created 10K NFT Collection featuring Praying Mantis Predators
Launched Early Contribution Program 
Launched First Airdrop Program
Q2 - 2022
Launched Smartnet Demo for public test 
Bug Bounty Program 
Closed Early Contribution Program with upgraded incentives for contributors
Q3 - 2022
Testnet Demo for Public Test 
Re-stage: Deploy Launchpad in Q3 2022 instead of 2023
Q4 - 2022
Set up Validator Node 
Start Code Audit & Review
NFT Staking MVP
Focus on Business Development while perfecting the platform
Q1 - 2023:
Complete Code Audit & Review
Mainnet Launch
Q2 - 2023:
Launch NFT staking
Launch NFT marketplace on Astar Network
Create fund to support NFT projects

**Comment by langdon0003** [comment]
Updated
