### ISSUE TITLE
Cannot set Duplication Check

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#116]
![Screen Shot 2023-02-08 at 10 06 28 AM](https://user-images.githubusercontent.com/88643486/217433826-7966c524-a2ff-4698-b2a7-5093952cf24a.png)
In Admin page, Cannot set Duplication to YES

**Comment by langdon0003** [comment]
Fix at commit [fe1be695b6ca20e72d46f774fac1040f33279ccc](https://github.com/ArtZero-io/frontend-react/commit/fe1be695b6ca20e72d46f774fac1040f33279ccc):


 fix typo to fix issue https://github.com/ArtZero-io/frontend-react/issues/116
