### ISSUE TITLE
Add DOXXED and VERIFIED Badge to NFT Collection

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#118]
DOXXED and VERIFIED Badge to add to: NFT Collection Page + NFT Collection Card

When clicking on DOXXED, show popup modal with message: At least one of team members verified his identity.

When clicking on VERIFIED, show popup modal with message: Artwork is verified by third-party for its uniqueness. Show Certificate Picture if exists

**Comment by nad128668** [comment]
![Screen Shot 2023-02-08 at 12 01 45 PM](https://user-images.githubusercontent.com/88643486/217438019-e2b1c368-91a7-4e61-a036-a68f53e49191.png)
On Collection Card, it should look like this for DOXXED and VERIFIED

**Comment by langdon0003** [comment]
<img width="284" alt="image" src="https://user-images.githubusercontent.com/35419213/217605258-70e4cae6-a6a9-4714-b2f5-f92ebb09f41e.png">
