### ISSUE TITLE
After Creating a Collection, Redirect to My Collections

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#119]
After Creating a Collection either in Advanced or Simple Mode, User should be Redirected to My Collections

**Comment by langdon0003** [comment]
please confirm, currently user will be stay on My Collection Tab after Add new Collection (2 modes) close.

**Comment by nad128668** [comment]
after created a collection in simple mode, redirect to https://alephzero.artzero.io/#/ not My Collection

**Comment by langdon0003** [comment]
update at [db6b9f5](https://github.com/ArtZero-io/frontend-react/commit/db6b9f5913e90e1d7930e52b741f520ca74e9be6)
