### ISSUE TITLE
Create Gap between Buttons

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#120]
![Screen Shot 2023-02-08 at 12 08 58 PM](https://user-images.githubusercontent.com/88643486/217439716-28fff971-cb4f-486a-92c3-69a8b8dc75a0.png)

**Comment by langdon0003** [comment]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/35419213/217620288-bce4a257-28cd-48b2-b986-69faa2d28872.png">
