### ISSUE TITLE
Cannot mint more than 6 NFTs in LaunchPad

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#121]
![Screen Shot 2023-02-08 at 9 53 30 AM](https://user-images.githubusercontent.com/88643486/217439852-183c79f8-0ef3-4726-9992-73b3e0b2f6c8.png)

**Comment by langdon0003** [comment]
Issue này e check thấy gas trên UI khi mint 10 con ko cao đến mức max. nên e có set x4 có mint thử 10 con ok rồi. a thử lại giúp e nhe
