### ISSUE TITLE
UI Slowness

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#123]
When Open following Modals: Add new NFT, Add new Collection. The UI appear to be very slow.

**Comment by mitchdoan** [comment]
yes its quite slow the photos need few seconds to load

**Comment by phoebehoang85** [comment]
5 mins after Owner Mint NFTs (22 NFTs in total), NFTs have not been shown in My Account \ My NFTs.

I ll check later, if NFTs do not appear, I'll create a new issue

![image](https://user-images.githubusercontent.com/107900832/217531742-f7c2bdde-93d8-457a-a733-29d71537e06b.png)

![image](https://user-images.githubusercontent.com/107900832/217531995-f3ecbcab-8932-4fa5-a834-520869576969.png)

**Comment by thienvip107** [comment]
fixed slow UI : modal create, collection, nft, nft detail .
Please check Internal version

**Comment by langdon0003** [comment]
Please review 
@nad128668 @mitchdoan
