### ISSUE TITLE
Project not doxxed or verified but show the badge

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#124]
![Screen Shot 2023-02-08 at 12 22 31 PM](https://user-images.githubusercontent.com/88643486/217441705-c22c7459-51ad-43a1-bfe1-2bdbcec0ebdf.png)
![Screen Shot 2023-02-08 at 12 23 04 PM](https://user-images.githubusercontent.com/88643486/217441752-154f2488-70e1-4bd7-86d0-8b4e9ceb3825.png)

**Comment by langdon0003** [comment]
Fix at commit [fe1be695b6ca20e72d46f774fac1040f33279ccc](https://github.com/ArtZero-io/frontend-react/commit/fe1be695b6ca20e72d46f774fac1040f33279ccc):
also:
- edit gas x4 to fix issue #121
- fix type to fix issue #116
