### ISSUE TITLE
NFT Owner cant list/unlist/accept bid in Collection Page

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#125]
When NFT owner is in Collection Page, he cannot perform: list/unlist/approve bid. He has to go to My NFTs to do so.

Add this feature to make UX better

**Comment by langdon0003** [comment]
Update later, atm user only can do it on NFT detail page and My NFT only

**Comment by langdon0003** [comment]
@phoebehoang85 please review

**Comment by phoebehoang85** [comment]
Review. Close case
