### ISSUE TITLE
contracts.OutofGas: The executed contract exhausted its gas limit

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#128]
when buying using "Buy Now" function on the collection Tornado#1 

the error show is

contracts.OutofGas: The executed contract exhausted its gas lomit

There is some error with your request

**Comment by langdon0003** [comment]
Error `contracts.OutofGas:` is fixed at commit  [e98f356d8387178d326ad3badbc7c7b23c9798ba](https://github.com/ArtZero-io/frontend-react/commit/e98f356d8387178d326ad3badbc7c7b23c9798ba).
