### ISSUE TITLE
Launchpad: Time-counting between phases incorrrect

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#129]
Time between phase 1 & 2 is currently 12 mins, countdown is incorrect

![image](https://user-images.githubusercontent.com/107900832/217484966-75567b58-f7db-4a61-921b-fa68037b8dbc.png)

![image](https://user-images.githubusercontent.com/107900832/217485181-84f0e59c-ee80-4ebb-9f96-f01285023c4f.png)

**Comment by phoebehoang85** [comment]
Since countdown is incorrect, when phase 2 is supposed to start, it actually does not start.

![image](https://user-images.githubusercontent.com/107900832/217488465-1859ef85-6372-4cd7-b83e-689f46d62b1a.png)

![image](https://user-images.githubusercontent.com/107900832/217488554-457fa223-f8d0-4884-9fba-0601a43f53b0.png)

**Comment by phoebehoang85** [comment]
After Refreshing, phase 2 already starts.

![image](https://user-images.githubusercontent.com/107900832/217490958-9d418a85-8145-4263-8261-1306b9d68710.png)

**Comment by langdon0003** [comment]
Fix at commit [6be6a45](https://github.com/ArtZero-io/frontend-react/commit/6be6a45f64447d17c58837bd075289f60f06352b).

**Comment by phoebehoang85** [comment]
If I wait for the countdown to run to 0 min 0 sec and change to the next phase, the time becomes -1 day -1 ...

Refresh, time seems to work ok.

Request to recheck.

![image](https://user-images.githubusercontent.com/107900832/218813793-44c3c0bd-ca88-4167-9296-e9ba3c569cc8.png)

**Comment by langdon0003** [comment]
Please review @phoebehoang85

**Comment by phoebehoang85** [comment]
Re-test OK, close case
