### ISSUE TITLE
API https://api.artzero.io/getBidsByBidderAddress return empty

### ISSUE THREAD

**Issue by langdon0003** [ArtZero-io/frontend-react#130]
Ví bid
5EfUESCp28GXw1v9CXmpAL5BfoCNW2y4skipcEoKAbN5Ykfn

collection GOKU 
5E3gyB76ht7v6ynR4phphg5po3MeknmqYUWWyYdMSSyKY4tS

bid 22A cho NFT GOKU #001

API https://api.artzero.io/getBidsByBidderAddress return empty []

expect return list of bid of user

**Comment by Albert-Tran** [comment]
Hi @langdon0003 , i fixed it. Please try it 
curl --location --request POST 'https://api.artzero.io/getBidsByBidderAddress' \
--header 'Content-Type: application/json' \
--data-raw '{
    "bidder": "5EfUESCp28GXw1v9CXmpAL5BfoCNW2y4skipcEoKAbN5Ykfn"
}'
