### ISSUE TITLE
Launchpad: Phase information incorrect when being at the countdown time

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#132]
Project has completed 2 phases and is at the countdown before 3rd phase.

In the dashboard, Phase price & Phase is at Phase 1.

Correct the phase price & phase name, should be the phase that will start next (in this case phase 3)

![image](https://user-images.githubusercontent.com/107900832/217534730-3d2687f0-039d-4a25-bc06-1d203f8c9dab.png)

![image](https://user-images.githubusercontent.com/107900832/217535033-487643f1-2f7f-443f-a91a-f0f281536a39.png)

**Comment by langdon0003** [comment]
Fix at commit [6be6a45](https://github.com/ArtZero-io/frontend-react/commit/6be6a45f64447d17c58837bd075289f60f06352b).

**Comment by phoebehoang85** [comment]
Re-test OK. Close case.
