### ISSUE TITLE
Launchpad > Owner Mint: NFTs not shown anywhere after owner mint

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#133]
Owner Mint NFTs (22 NFTs in total), NFTs have not been shown in either My Account \ My NFTs, or Marketplace (there should have been 24 NFTs in this collection - 2 minted by a user, 22 owner minted)

![image](https://user-images.githubusercontent.com/107900832/217531742-f7c2bdde-93d8-457a-a733-29d71537e06b.png)

![image](https://user-images.githubusercontent.com/107900832/217531995-f3ecbcab-8932-4fa5-a834-520869576969.png)

![image](https://user-images.githubusercontent.com/107900832/217540395-7df73d77-3876-44c2-b267-0037318a1b4e.png)

**Comment by langdon0003** [comment]
Pizza NFT not appear due to not be cached. Please waiting for Cuong @Albert-Tran done his side.
