### ISSUE TITLE
Launchpad > Update phases: impossible to update a phase

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#134]
Impossible to update a phase. Tried updating number of NFTs / time / max mint of phase 4, all impossible.

![image](https://user-images.githubusercontent.com/107900832/217545681-6e49f7c5-1fdc-4548-8d64-3e3155cd3863.png)

**Comment by langdon0003** [comment]
Need @phoebehoang85 you provide more info about which field be change failed. 

I did try with name of phase change from `phase 3` to `phase 3 EDIT` and still work as expect.

**Comment by langdon0003** [comment]
@Albert-Tran pls check this case:
- Input from FE, all same except name `Phase 4` to ``Phase 4 EDIT
<img width="255" alt="image" src="https://user-images.githubusercontent.com/35419213/217626778-0a888b86-737d-477b-ab1b-f6a899651d8e.png">
- call FE got contract Revert as @phoebehoang85 upload above
- tried with contract UI and get   "Custom": "cannot update phase"
err & input from contract UI as below image
<img width="511" alt="image" src="https://user-images.githubusercontent.com/35419213/217627381-beeaaee4-f8e5-4463-8dd6-1c3b38908b6b.png">

**Comment by Albert-Tran** [comment]
I have checked this issue:
The phase has whitelisted an account so we can't update this phase. Could u please make sure this logic on frontend if the phase can't be updated, u need to disable or hide the edit button and show an alert on this phase ? 
@langdon0003

**Comment by langdon0003** [comment]
- Add check WL added for edit phase at commit [d927d7241e7c5425951b727b31fdd1df94467e20]()

**Comment by phoebehoang85** [comment]
Re-test: can edit a phase successfully if there is no whitelist & phase has not started.

Re-test: cannot edit a phase once there is a whitelist.
