### ISSUE TITLE
Launchpad > Update project info > Royalty fee always 0.5% + cannot hit Update project button

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#135]
I set project at 3%. When I went to Update project info, Royalty fee is 0.5% and cannot be changed. It should be according to Royalty fee that owner have set.

Can we change royalty fee anywhere?

Plus, I cannot hit UPDATE PROJECT button at the end.

![image](https://user-images.githubusercontent.com/107900832/217621897-38540906-87d4-45b6-99bd-d6b592b1109e.png)

![image](https://user-images.githubusercontent.com/107900832/217621947-0ce5a3f9-cae0-4fa7-9bb1-f68b6109ab3f.png)

![image](https://user-images.githubusercontent.com/107900832/217624322-a273caac-cde4-4542-8a84-f78256444211.png)

**Comment by langdon0003** [comment]
Royalty fee always 0.5% 
=> Royalty fee currently not allowed to change after create (proj, 2 collection 2 mode)
- temp fix can not submit due to miss telegram data field.

#144 still waiting for @Albert-Tran update API

**Comment by langdon0003** [comment]
[1958618](https://github.com/ArtZero-io/frontend-react/commit/195861888ab2a6c70d4c60a08d4553a8610d91f9) 
Fix not show telegram field 
Fix show royalty Fee

**Comment by phoebehoang85** [comment]
Re-test OK, close case
