### ISSUE TITLE
Create balance report for Owner

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#136]
When withdraw balance, we need to show Owner a balance report, summarizing all transactions that he gets the revenue, when / what amount he withdrew before, how much is left.

**Comment by nad128668** [comment]
@Albert-Tran add events vào contract và backend
withdraw_fee + public_mint + whitelist mint psp34_launchpad

**Comment by phoebehoang85** [comment]
Close case.
