### ISSUE TITLE
Aleph Zero Faucet informed sent 25001 TZero but not updated in Subwallet

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#138]
I tried 2 times today, after using faucet to get test Tzero it is said sent 25k Tzero but after 2 hours the subwallet still show 0 Tzero. This will cause user to be unable to do any transaction on the artzero.io page

**Comment by langdon0003** [comment]
update new link for testnet faucet (TZERO). sorry for this inconvenient.
