### ISSUE TITLE
Term of Service link artzero.io/contact-us not working well

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#140]
it route to home page of Artzero and make the address in the browser blank![image](https://user-images.githubusercontent.com/117429099/217657981-7f7fffa9-a0fe-44b3-b69f-783751fa343b.jpeg)

**Comment by langdon0003** [comment]
please provide more detail where you find link to artzero.io/contact-us ?

**Comment by mitchdoan** [comment]
in the Terms of Service at the page bottom

**Comment by langdon0003** [comment]
@phoebehoang85 
![image](https://user-images.githubusercontent.com/35419213/218502442-303372f9-32a7-4ec7-a2aa-2072f93c43f8.png)

**Comment by phoebehoang85** [comment]
@langdon0003 Either you create a link /contact-us where people can filll in forms, then email to support@artzero.io, or replace with the email support@artzero.io

**Comment by mitchdoan** [comment]
pls proceed with one of the suggestions @langdon0003

**Comment by langdon0003** [comment]
Please review @mitchdoan

**Comment by mitchdoan** [comment]
strange, now all the ToS, Privacy Policy disappear from both artzero.io and alephzero.artzero.io em ạ @langdon0003
