### ISSUE TITLE
Confusing about My Account

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#141]
My Account has a list of dropdown options but all except one show to the same My account page, while another section Accou...address only has the Disconnect wallet

users might confuse where is correct my account

**Comment by langdon0003** [comment]
@mitchdoan need more explain about the expected case.

**Comment by mitchdoan** [comment]
expected: only one My Account/Account management area

**Comment by langdon0003** [comment]
You mean:
<img width="314" alt="image" src="https://user-images.githubusercontent.com/35419213/218041042-1763cac0-891b-45fe-8ac7-b6fd8f00d41a.png">

change to:
<img width="221" alt="image" src="https://user-images.githubusercontent.com/35419213/218041341-a2abfc1c-38b0-45aa-86cf-10d224d2aa02.png">
