### ISSUE TITLE
PMP Collection Images not loading

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#143]
![Screen Shot 2023-02-09 at 10 14 53 AM](https://user-images.githubusercontent.com/88643486/217708890-2a5f13e1-83da-41d0-b878-10411513eecb.png)

![Screen Shot 2023-02-09 at 10 16 21 AM](https://user-images.githubusercontent.com/88643486/217708998-454832a1-e7a9-4fe9-94bd-9014cdd16733.png)

**Comment by langdon0003** [comment]
<img width="471" alt="image" src="https://user-images.githubusercontent.com/35419213/217716935-42ffe7af-7262-4cb9-a863-dd8d88fccd38.png">
Need double check from Backend side @Albert-Tran
