### ISSUE TITLE
Change Menu Order

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#145]
![Screen Shot 2023-02-09 at 1 13 30 PM](https://user-images.githubusercontent.com/88643486/217732816-1cb4ba9b-2171-4b0c-a369-d2ebc5b67472.png)

Move **Create** button from main menu to My Account Sub Menu and change to **Create Collection** place it between **General** and **My Collections**

Move **Stake To Earn** from My Account sub Menu to Main Menu Between **LaunchPad** and **Stats**. Change to **Stake2Earn**

**Comment by langdon0003** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/35419213/217757053-a0e89d36-7ac6-4d89-bd72-e5bbd53963e0.png">
Done at commit [66973a7](https://github.com/ArtZero-io/frontend-react/commit/66973a7d8121eef9007dbeaf469a7fe82f78a8ad)
