### ISSUE TITLE
My Account > General : Trade Fee & Total Owned NFTs displayed incorrect

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#148]
Trade fee & total owned NFTs displayed incorrect.

5 PMPs staked --> Trade fee 2.5%
Total owned NFTs: 25 NFTs + 5 PMPs

![image](https://user-images.githubusercontent.com/107900832/217782519-f3b09a49-1769-47f0-b4c3-62381d491b81.png)
 
![image](https://user-images.githubusercontent.com/107900832/217782673-ca3c2a22-c929-49f7-8f3d-3f1d9ab4390c.png)

**Comment by langdon0003** [comment]
Fix at commit [8132103](https://github.com/ArtZero-io/frontend-react/commit/813210383059b864128c54cc30692e86bb07a33e)
**Note:**
Dashboard now have number of NFT for sale, NFTs staked, NFTs pending unstaked and Total (include available in Collected Tab)

The total number still need Backend API to be fixed to be show the right number (It should be less than current (not include NFT of owner of inactive collection)) at issue #164 `API /getNFTsByOwner need add 1 more () isActive = true`

**Comment by phoebehoang85** [comment]
re-check: Trade fee & total owned NFTs displayed correct.
