### ISSUE TITLE
Admin > Rewards Distribution: Cannot claim marketplace balance

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#149]
Cannot claim marketplace balance: button Claim Balance for marketplace seems not working.

Claim balance for Collection & Launchpad work fine.

![image](https://user-images.githubusercontent.com/107900832/217893946-6f0f86d0-cfcf-4434-ada0-fad9a81cdc88.png)

**Comment by langdon0003** [comment]
Fix at commit [3c5533b](https://github.com/ArtZero-io/frontend-react/commit/3c5533b5c6b62032f873fc83e784702411e43e53)

**Comment by phoebehoang85** [comment]
Re-test: Claim marketplace balance successfully. Close issue.
