### ISSUE TITLE
Admin > Reward Distribution: Cannot lock staking

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#150]
Cannot lock staking. Used Albert ...Ykfn 

![image](https://user-images.githubusercontent.com/107900832/217897330-1d5bd051-07c2-4fe7-90db-21e217e0e88d.png)

**Comment by langdon0003** [comment]
Fix at commit [9ccb820](https://github.com/ArtZero-io/frontend-react/commit/9ccb820b3586c260ba633e46bd7680a431b62034)

**Comment by phoebehoang85** [comment]
Re-test: Lock staking successfully. Close issue.
