### ISSUE TITLE
Lock metadata: If address is not the owner of the NFT, hide button LOCK METADATA

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#151]
If address is not the owner of the NFT, hide button LOCK METADATA

![image](https://user-images.githubusercontent.com/107900832/217902941-3c627bc3-5376-4991-ac95-6abcd0da0493.png)

**Comment by langdon0003** [comment]
change: hide Lock Icon component. need confirm @nad128668
