### ISSUE TITLE
When Create Simple Collection, if user cancel signin, it leads to deadlock

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#152]
- click Create collection
- choose Simple Mode
- Fill in all the details, click Create Collection
- Wallet pop up, click close
- Now whole page is in deadlock mode cant do anything else

@langdon0003 kindly help to support, thanks em

**Comment by langdon0003** [comment]
May be need a call to explain.

Current situation:
Wallet only support auto cancel pending transaction by click `Cancel` or `Reject`.
In case user click close icon ❌ , transaction just hide back to add-on on the top right of browser like this.
<img width="54" alt="image" src="https://user-images.githubusercontent.com/35419213/218078544-70131868-18a8-4c7c-b5cb-008e9fe9f83d.png">.
If user keep able to click to create new action, it still popup new window to sign but it's the old one with note on pop up is "1/2" and the real one is the later one. (the second sign. 2/2)

But when user not pay attention the the seque then sign it will show error with "Out dated" transaction.
cause it occur before so temp solution is att a toast to warning user about pending transaction and disable All function button to prevent "Out dated" issue.

Need more guideline and feedback about solution for both case.

**Comment by langdon0003** [comment]
Normal solution as my personal exp is; click on add-on icon and cancle or rejcet it. All things will back to normal.
![image](https://user-images.githubusercontent.com/35419213/218081295-650819cf-8356-4dcf-9666-3b15a4690fca.png)

![image](https://user-images.githubusercontent.com/35419213/218081368-f229ed03-cdba-4f9d-9de0-da4f592b7fc6.png)

**Comment by mitchdoan** [comment]
sure we can have a call
