### ISSUE TITLE
Add Levels the max value can be > 10, while they doesnt allow min value to be >10

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#154]
level at min can only be up to 10, but the max value can be bigger than 10 i put 70 it still accept,can save collection [image](https://user-images.githubusercontent.com/117429099/217924691-8fe8b890-0aa1-4191-b741-62b0e468de8e.jpeg)
![image](https://user-images.githubusercontent.com/117429099/217925109-4b6b422e-2279-418e-aa69-4809023f2281.jpeg)

**Comment by langdon0003** [comment]
Fix at commit [6511d2b](https://github.com/ArtZero-io/frontend-react/commit/6511d2bf8d0cbc8edbdd377644233666c1f37745)
