### ISSUE TITLE
the close icon of Create Collection - Simple Mode on top of address difficult to see for customer

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#155]
simple mode once its open and we dont want to create any more then we close but the close button is on top of address very difficult to spot

browser = firefox

![image](https://user-images.githubusercontent.com/117429099/217927201-1c95775b-f79f-4532-831d-a9795a4add2f.jpeg)

**Comment by langdon0003** [comment]
Need more info about your brower config.

Currently, background will blur on all case Modal open.

That's kind of weird but I tried all kind of browsers as below.

I check on:
- my Window/Chrome
<img width="225" alt="image" src="https://user-images.githubusercontent.com/35419213/218146008-f70a69e7-f322-4ffa-8fba-9bf0536a915d.png">

- my Window/MS EDGE
<img width="195" alt="image" src="https://user-images.githubusercontent.com/35419213/218146281-f513fa0c-8730-4ab3-bc68-fdc1e47f74b0.png">

- my Window/Firefox
<img width="183" alt="image" src="https://user-images.githubusercontent.com/35419213/218146792-4d34d4af-7bec-47f9-b6d2-76703e933dbf.png">


- my Window/Opera (Not wallet add on install but still blur background)
<img width="333" alt="image" src="https://user-images.githubusercontent.com/35419213/218147145-7973d5ed-c832-4be6-a507-19e9d86a09b5.png">

- my Window/Brave
<img width="239" alt="image" src="https://user-images.githubusercontent.com/35419213/218147661-e0e9ee5c-b536-43f5-8191-cedc0c23477f.png">

**Comment by mitchdoan** [comment]
yeah it is strange, the text buttons on the top bar are still visible from my firefox
