### ISSUE TITLE
Profile Avatar not updated after successfully change

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#156]
profile photo accepted and uploaded with status Ready but after that it disappear

![image](https://user-images.githubusercontent.com/117429099/217930471-c5d6cfae-638b-4902-a2cc-6ef0bd9ab374.jpeg)

![image](https://user-images.githubusercontent.com/117429099/217930744-f9184dcc-5a8d-4692-8ee5-173833678bc2.jpeg)

**Comment by langdon0003** [comment]
Need explain on Call
