### ISSUE TITLE
Refresh in My NFTs/ My Collected doesn't work

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/frontend-react#163]
My collected has an NFT.

![image](https://user-images.githubusercontent.com/97796421/218003444-98f6d73f-c662-4d29-8e22-4d27065252d0.png)

Press the refresh button, it shows the message "No NFT found."

![image](https://user-images.githubusercontent.com/97796421/218003655-72104a67-997a-4690-a1bf-79e05822d5b1.png)

**Comment by langdon0003** [comment]
Fix at commit [a7c0ff4](https://github.com/ArtZero-io/frontend-react/commit/a7c0ff4f7d35788135bd2391f59f340b3ad57bc0)

**Comment by hnnam0906** [comment]
Fixed
