### ISSUE TITLE
Admin > Reward Distribution: disable button when completing steps of rewards distribution

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#165]
When completing each steps of rewards distribution, we should disable that button, so we know at which step we are at.

I have Lock Staking successfully. But after that, I come back Lock Staking again, transaction is still possible to do although it is not harmful.

So, after Lock staking successully, we should disable Lock Staking button.

Similarly, after Step 4, Step 5, Step 6, buttons should be disabled.

When Step 6 Unlock Staking Contract, enable all buttons again so the next round of reward distribution can be done next mth.

![image](https://user-images.githubusercontent.com/107900832/218155230-e48e4ead-4a86-47d1-95c6-a9c9c7db8768.png)

**Comment by langdon0003** [comment]
Update at commit [f9bffa0](https://github.com/ArtZero-io/frontend-react/commit/f9bffa029827348795006c1ace01b5a797394609)

**Comment by phoebehoang85** [comment]
Re-test OK. Close case.
