### ISSUE TITLE
Update Phase: Sometimes when clicking button Update phases, a strange window appear

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#166]
Sometimes when clicking button UPDATE PHASES, a strange window pops up. I have to close it and click the button again. Then the right window pops up to allow phase changes.

![image](https://user-images.githubusercontent.com/107900832/218166385-667389be-b150-4de0-9a03-8b120d5f9fa6.png)

![image](https://user-images.githubusercontent.com/107900832/218166151-8a1c9c51-4023-42ca-81a3-52a5070ca61c.png)

**Comment by langdon0003** [comment]
Fix at commit [9c05c85](https://github.com/ArtZero-io/frontend-react/commit/9c05c850c6a65f21640bd6340d1bb1deea522f64).
Add loader for case slow internet connection, or quick click Update Phase after Proj Page loaded.

**Comment by phoebehoang85** [comment]
Re-test OK. Close case.
