### ISSUE TITLE
Add whitelist: impossible to remove whitelist / updating number of whitelist NFTs to 0

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#167]
Impossible to remove whitelist.

We should allow owner / admin to remove whitelist by updating the number of whitelist NFTs to 0.

![image](https://user-images.githubusercontent.com/107900832/218167810-7a43848a-5f74-4f9f-b3f1-bd065e6d3e3e.png)

**Comment by langdon0003** [comment]
Fix add commit [d018947](https://github.com/ArtZero-io/frontend-react/commit/d018947a8daf43334b8c3b2cbd94363ffa939ae2)

**Comment by phoebehoang85** [comment]
when updating amount to 0 NFT is it possible to erase the row?

![image](https://user-images.githubusercontent.com/107900832/218807857-ffb89779-974f-4a2b-92b0-0e9bb337993d.png)

**Comment by langdon0003** [comment]
Please review @phoebehoang85 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/35419213/218922737-872faf85-ddce-4c69-a6f2-918edb22b705.png">

**Comment by langdon0003** [comment]
Please review @phoebehoang85
