### ISSUE TITLE
Why Levels only to 10? and it should be unlimited

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#168]
Dear Artzero Team, I saw the level option of NFTs are limited to 10. I think it should be unlimited values. For example  kg levels like 7324 of 425000 kg

and can display in a sliding bar like below

![image](https://user-images.githubusercontent.com/117429099/218279730-8989d28e-1106-4be1-8706-0abb667ac7af.png)

**Comment by langdon0003** [comment]
Fix level able to set to over 10 now at commit [6511d2b](https://github.com/ArtZero-io/frontend-react/commit/6511d2bf8d0cbc8edbdd377644233666c1f37745)

A sliding bar will be added in the next release.

Thanks for feedback
