### ISSUE TITLE
NFT Images not shown 

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#169]
![Screen Shot 2023-02-13 at 9 10 18 AM](https://user-images.githubusercontent.com/88643486/218355064-5c42a121-1422-4a0e-a02f-8d4dd6f6596a.png)
PMP Collection
Pizza Collection

**Comment by Albert-Tran** [comment]
Hi @nad128668 , i cached the Pizza collection 
[https://alephzero.artzero.io/#/collection/5En6YCXWFdViJNBP4FjGuB3mphKX9vKUpAMrQbhJAkWigpGH](url)
![image](https://user-images.githubusercontent.com/53705980/218380744-587840ca-d94e-4697-92d4-b8aebc8e9559.png)

**Comment by nad128668** [comment]
PMP collection still not shown

**Comment by Albert-Tran** [comment]
Hi @nad128668 , i cached 300 nfts of PMP collection
![image](https://user-images.githubusercontent.com/53705980/218425785-84ae83ac-07e0-424f-96d0-04ecad4c776c.png)
