### ISSUE TITLE
Add Telegram and Email when creating new Project or new Collection

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#170]
At the moment, only Email input asked during creation of a new Project. 
Telegram and Email should be on the form when creating new Project or new Collection (Simple and Advanced Mode)

The Email will be sent to both Admin and Creator

Email Template for Admin email:
```
Title: New Project/Collection

Dear team,

New project/collection from {email}
Telegram ID: {telegramID}
Collection Address: {collection_address}

Best Regards
```
Email Template for Creator email:

```
Title: Project/Collection created successfully

Dear creator,

Thank you for creating new {Project on ArtZero's Launchpad, Collection on ArtZero}. We will contact you for further instructions via provided email {email} or Telegram ID {telegram_id}.

Best Regards,
ArtZero Support Team

```

**Comment by langdon0003** [comment]
Updated, please review email content.

**Comment by langdon0003** [comment]
Please review @phoebehoang85 @nad128668 

### Suggestion

```
Dear creator,

Thank you for creating new Collection/Project "{{project_name}}" - address {{nft_address}} on on ArtZero. 

We will contact you for further instructions via provided email {{email_owner}} or Telegram ID {{collection_telegram}}.

Best Regards,
ArtZero Support Team
```

### Sample email.

```
Subject: Collection/Project created successfully.

Dear creator,

Thank you for creating new Collection/Project "ABC" - address 5Cyp6ZYr6WpqdV7M878NphBGpthJvuo2ZRW6HArpQp5zrHeC on on ArtZero. 

We will contact you for further instructions via provided email [abc@gmail.com](mailto:abc@gmail.com) or Telegram ID https://t.me/LA123123123.

Best Regards,
ArtZero Support Team
```

**Comment by nad128668** [comment]
@phoebehoang85 @mitchdoan

**Comment by mitchdoan** [comment]
Dear [NFT Collection Creator],

I am writing to confirm that your NFT collection {project_name} has been successfully submitted to the ArtZero NFT marketplace. We appreciate your interest in our platform and look forward to featuring your unique collection.

Our team will carefully review your submission and ensure that it meets our quality standards. Once your NFT collection has been approved, it will be listed on our marketplace for buyers to discover, buy, and trade.

Please note that the review process may take up to [number of days/weeks] to complete. We will contact you via email {email} or Telegram ID {telegram_id} for further instructions.

In the meantime, if you have any questions or concerns regarding the submission process, please do not hesitate to contact us at [ArtZero Email Address]. We are here to assist you throughout the process.

Thank you for choosing to list your NFT collection on our platform. We appreciate your cooperation and look forward to working with you.

Best regards,

Shinie

ArtZero Support Team

**Comment by phoebehoang85** [comment]
Email format confirmed. Close case.
