### ISSUE TITLE
Incorrect menu link on mobile version

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#172]
![D238CB13-66C0-4551-8EA8-337308184A2F](https://user-images.githubusercontent.com/88643486/218608227-342812a4-6ffc-4a31-a065-7056415e0f2f.png)

Stake2earn on Mobile version doesnt link to inkwhale but open artzero gitbook

**Comment by langdon0003** [comment]
Please review @nad128668
