### ISSUE TITLE
Trade Discount table shows too many decimals

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#176]
![Screen Shot 2023-02-14 at 10 21 31 AM](https://user-images.githubusercontent.com/88643486/218630921-1a3f83c1-6c24-46af-8a7b-d93050b70c62.png)

This is on Shibuya network, but on Aleph Zero the issue also exists

**Comment by langdon0003** [comment]
Azero is ok, please confirm 
<img width="505" alt="image" src="https://user-images.githubusercontent.com/35419213/218649918-edd23dc5-0cb8-4dbd-94e9-fcfe35e2460f.png">
