### ISSUE TITLE
Error when clicking next page after entering the page number

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#178]
## Describe the bug
Error when clicking next page after entering the page number.

## To Reproduce
1. Go to https://alephzero.artzero.io/#/collection/5FkVyhF4KVMwgVTbRwvDgnJ7oe8tfZ9A7v2sEiqQPccHkUNC?is_for_sale=false
2. Enter 24 into "Go to page"
3. Click Next icon
4. See error "Page 241 of 67"
=> Correct display is "Page 25 of 67"

## Priority
What is the impact of this bug on the user, how critical is to fix? 
 Enhance

## Screenshots/Video
![image](https://user-images.githubusercontent.com/102939807/218993939-3b9e416f-cccd-43ac-a23c-a844e1b0cb2d.png)

**Comment by langdon0003** [comment]
Update at commit [a985916](https://github.com/ArtZero-io/frontend-react/commit/a98591634108e05b2a1304186d28820bd093e454) & [2531211](https://github.com/ArtZero-io/frontend-react/commit/2531211952fece3c78949ca5450e5b83a172f768).

**Comment by vup2p** [comment]
displayed correctly
