### ISSUE TITLE
(Mobile) levels show not horizontal

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#181]
![image](https://user-images.githubusercontent.com/117429099/219379029-2cff161c-4234-4ce8-a47f-820f98ea7eaa.png)

**Comment by langdon0003** [comment]
Fix add commit [cdbab23](https://github.com/ArtZero-io/frontend-react/commit/cdbab230fb0108ff0e401b5671e1826ed2ac5316)
