### ISSUE TITLE
(Mobile+Web) Add Properties/add level should be Edit properties/edit level

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#182]
because in Add properties you can delete properties and edit properties as well

similarly for Add levels

![image](https://user-images.githubusercontent.com/117429099/219379672-9c3b4a6d-ae0a-46f4-96b7-0719dc6fa328.png)

**Comment by langdon0003** [comment]
Update at commit [cdbab23](https://github.com/ArtZero-io/frontend-react/commit/cdbab230fb0108ff0e401b5671e1826ed2ac5316).
