### ISSUE TITLE
(Mobile) button edit nft cant function when on sale , can remove it

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#183]
![image](https://user-images.githubusercontent.com/117429099/219380430-9730c934-5431-4724-b9c5-9a4afe8167f3.jpeg)

**Comment by mitchdoan** [comment]
@langdon0003 as discussed, when on sale this button can be hidden

**Comment by mitchdoan** [comment]
@langdon0003 em update giup a nhe

**Comment by thienvip107** [comment]
![image](https://user-images.githubusercontent.com/42136863/221734825-c9f619b9-6d98-4eb0-bde2-0e0d68475de6.png)
Can't procedure
