### ISSUE TITLE
(Mobile) Edit NFT display as Simple

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#186]
![image](https://user-images.githubusercontent.com/117429099/219672657-b0ada74a-551f-4150-802c-90b9bec1e37f.jpeg)

**Comment by langdon0003** [comment]
@mitchdoan . that tag for info purpose, like example below. 
- Adv is collection created by Advanced Mode/Project launchpad
- Simple is collection created by Simple Mode
<img width="493" alt="image" src="https://user-images.githubusercontent.com/35419213/219989908-c90df789-edda-4934-8a1d-a9dff34d839c.png">

**Comment by mitchdoan** [comment]
but the button Simple has no meaning

**Comment by nad128668** [comment]
Remove Simple/Advanced Label in My Collection

**Comment by mitchdoan** [comment]
pls proceed to remove Simple/Advanced in above scenario @langdon0003

**Comment by langdon0003** [comment]
Please review @mitchdoan

**Comment by mitchdoan** [comment]
okay look fine, but can display as Edit as well![image](https://user-images.githubusercontent.com/117429099/221084115-803afe6e-b824-41fb-a816-56ca0e1b1ba7.png)
