### ISSUE TITLE
(Mobile+Web) Unnecessary note at NFt attributes

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#187]
Gold attribute, click on it it noted Gold, a bit duplicated and unnecessary ![image](https://user-images.githubusercontent.com/117429099/219676208-a35ac2f0-4d1f-487a-830e-001369381721.jpeg)

**Comment by langdon0003** [comment]
@mitchdoan. this for the case trait name too long and can not show full text as below.

<img width="326" alt="image" src="https://user-images.githubusercontent.com/35419213/219995375-e88bb72a-c5f1-4198-8056-6e054575d447.png">
