### ISSUE TITLE
(Mobile+Web) Mint phase message adjust

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#188]
if user own 0 NFT then no need to display msg: scroll down to see your nft

![image](https://user-images.githubusercontent.com/117429099/219679389-ed8fba93-3ff1-4ac1-970f-ce6e4c16fdd0.png)

**Comment by langdon0003** [comment]
updated at commit [d374c94](https://github.com/ArtZero-io/frontend-react/commit/d374c941fc2f748779be5265dd853483abd8116a)
