### ISSUE TITLE
(Mobile+Web) Price filter is not working

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#189]
![image](https://user-images.githubusercontent.com/117429099/219823508-c60fe62c-8857-41c4-9acf-cb18ad74142c.png)

**Comment by langdon0003** [comment]
@mitchdoan You need  click on PRICE FILTER button to apply it.

![image](https://user-images.githubusercontent.com/35419213/219997302-46e2c9b2-0426-40c1-839e-520a6a413213.png)

**Comment by mitchdoan** [comment]
but after clicking Filter, the window stay still, we need to close it to see result, can it display right after clicking Price Filter?

**Comment by mitchdoan** [comment]
@langdon0003 please help to update

**Comment by langdon0003** [comment]
@mitchdoan please review
