### ISSUE TITLE
Don't show NFT in staked

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#209]
## Describe the bug
Don't show NFT in staked because token_id field with comma

## To Reproduce
1. Go to [Homepage/#/account/stakes](https://alephzero.artzero.io/#/account/stakes)
2. Select STAKED

## Expected behavior
Show all NFT is staked

## Priority
What is the impact of this bug on the user, how critical is to fix? 
Urgent 

## Screenshots/Video
![image](https://user-images.githubusercontent.com/102939807/223675800-6fb38360-9953-4a85-9caa-89bbaf995ab8.png)

**Comment by langdon0003** [comment]
@vup2p please review. Re test with single/mutil stake, worked as expect.
