### ISSUE TITLE
Internal: Accept bid calculate wrong sale

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#210]
Collection: https://artzero-internal.pages.dev/#/collection/5CFaEptRQb6yqV5ebx25aF1jdsqtKC1mzVxeghAeDHmFhWMY?is_for_sale=false

NFT City Street #1

Owner ...x1oC list for 100A, trade fee 3%, royalty 4% (beginning balance: 91,204.30, end balance 91,204.26) --> OK
Address ...fZCk bid for 90A (beginning balance: 531,902.95, end balance 531,812.93) --> OK
Owner ...x1oC accept bid 90A (beginning balance: 91,204.26, end balance 91,391.04) --> increased by 186.78??? --> right number: increased by 90x(1-3%)=87.3 minus little gas fee

Owner history & Transaction history dupicated many times

![image](https://user-images.githubusercontent.com/107900832/223786232-b7136d35-62bc-4c15-9f4c-f97e19a46949.png)

![image](https://user-images.githubusercontent.com/107900832/223786263-24e0756f-d79b-44f2-9592-37b4484b40d4.png)

![image](https://user-images.githubusercontent.com/107900832/223786308-a22e692f-db6e-4eaf-ac7c-3657d46d23fc.png)

**Comment by thienvip107** [comment]
fixed duplicate history, em check block number trên explorer thì tiền trả về đúng ạ 
https://azero.dev/?rpc=wss%3A%2F%2Fws.test.azero.dev#/explorer/query/25474895

**Comment by phoebehoang85** [comment]
Reviewed. Close case.
