### ISSUE TITLE
Project page: Split pick Start/End time component into 2 separate component

### ISSUE THREAD

**Issue by langdon0003** [ArtZero-io/frontend-react#213]

**Comment by langdon0003** [comment]
@hnnam0906 @phoebehoang85 
Please review, Update sample solution at Project Start/End time
![image](https://user-images.githubusercontent.com/35419213/226843666-bf5849f9-7a42-46b7-9205-4e456855123c.png)

**Comment by hnnam0906** [comment]
I'm ok but also need to change for update phases func.
@phoebehoang85: how about you?
