### ISSUE TITLE
Internal: View an user's account nên thay đổi 1 số thông tin

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#218]
Nếu click vào address của user, ví dụ:

![image](https://user-images.githubusercontent.com/107900832/225065338-460c1d73-0f6b-4dd0-bef6-cbe1fbd8961e.png)

link:
https://artzero-internal.pages.dev/#/public-account/general/5CBTkRYt55mb6qHVWUMV8K61wyARrUM1we5nXZYvE7RpDfSx

![image](https://user-images.githubusercontent.com/107900832/225065851-6eb188c5-6c3d-4484-9c49-2b7fc9bc8c12.png)

>>>  Có nên để nút Stake ở đây không vì đây là trang của user khác? Các thông tin khác như Trade fee cũng có nên show public như vậy không?

![image](https://user-images.githubusercontent.com/107900832/225066084-34bc2260-fdc5-4c87-8b8c-3ef1d2b515f4.png)

![image](https://user-images.githubusercontent.com/107900832/225066260-68916c6b-c32c-492c-a891-afa072c76d20.png)

>>>  There are no collections.

**Comment by thienvip107** [comment]
vì tab general chứa nhiều infor cá nhân nên em để lại 3 tabs ạ

**Comment by phoebehoang85** [comment]
3 tabs ok đấy nhưng chị thấy dữ liệu đang k chính xác. Ví dụ: Project Pizza đang của ví owner 5E2AAyU33VsQDGDJh1S7wHpcQFhX8BPtJLpQs5UiU8aDx1oC mà check address nào cũng có project Pizza. 

Em kiểm tra lại các tabs xem có chuẩn owner của collection / nfts / projects chưa? @thienvip107 

![image](https://user-images.githubusercontent.com/107900832/225559780-1d405c41-563c-4de5-b661-27aa301b27a0.png)

**Comment by phoebehoang85** [comment]
Nếu vào Profile page của 1 user và xem được NFT / Collection của user đó, nhưng không click được vào NFT / Collection của user đó để xem tiếp
--> cho phép click vào để xem và thực hiện tiếp các actions: buy / bid NFT đó, hoặc click vào Collection hoặc Project để ra tiếp trang detail của Collection hoặc Project đó. @thienvip107 @langdon0003 

![image](https://user-images.githubusercontent.com/107900832/226687361-ecdfd8ec-34ce-437c-858f-5ae096845c7f.png)

**Comment by thienvip107** [comment]
hiện tại đang click vào tên của collection, project để vào collection detail, project detail rồi ạ

**Comment by phoebehoang85** [comment]
reviewed & close case.
