### ISSUE TITLE
Internal: không remove được admin role

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#225]
Trước đây khi chỉ add được 1 admin, thì khi update admin mới thì remove admin cũ. Hoặc muốn remove admin mà không add admin nào mới thì add chính mình làm admin.

Hiện cho phép add nhiều admin nhưng không remove được admin.

Ngoài ra owner đang không xem được hiện ví nào là admin của mình.

Ví dụ pizza đang có 2 admin nhưng không hiển thị ở đâu

![image](https://user-images.githubusercontent.com/107900832/225087074-e0a8def4-9fba-4a89-a7e3-3783aa07f589.png)

**Comment by langdon0003** [comment]
TODO:
- [ ] Update Modal for Admin List, Grant/Remove Grant

**Comment by langdon0003** [comment]
@phoebehoang85 
Please review
![image](https://user-images.githubusercontent.com/35419213/226847028-2935d05c-f42c-4e63-9dc5-b596e8e5997d.png)

**Comment by phoebehoang85** [comment]
Close case.
