### ISSUE TITLE
Internal: Phase kết thúc rồi vẫn add được whitelist

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#227]
Hiện phase kết thúc rồi vẫn single add được whitelist.

Sửa lại để không add whitelist cho những phase đã kết thúc.

![image](https://user-images.githubusercontent.com/107900832/225561054-376a9a46-b241-49f7-af80-42861e55f7ec.png)

**Comment by langdon0003** [comment]
please review @phoebehoang85

**Comment by phoebehoang85** [comment]
Close case.
