### ISSUE TITLE
Bulk add whitelist issue

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/frontend-react#234]
Bulk add whitelist func shows message "Cannot add whitelist to inactive phase" while still can use Single add whitelist mode.

![image](https://user-images.githubusercontent.com/97796421/226692187-2a18b368-7ae6-4674-902f-bd2dba559612.png)

**Comment by langdon0003** [comment]
@hnnam0906 please review

**Comment by hnnam0906** [comment]
It is ok now. Thks.
