### ISSUE TITLE
Still display WL address for single mode while in bulk add WL mode  

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/frontend-react#235]
![image](https://user-images.githubusercontent.com/97796421/226693253-9b9cb6a2-ba19-46c7-9eff-0ec35b6a9f39.png)

**Comment by langdon0003** [comment]
@hnnam0906 
please review
![image](https://user-images.githubusercontent.com/35419213/226853454-e158e09b-da20-4519-b496-fa04722c7a7c.png)

**Comment by hnnam0906** [comment]
It is ok.
