### ISSUE TITLE
No opt for editing whitelist

### ISSUE THREAD

**Issue by hnnam0906** [ArtZero-io/frontend-react#238]
![No option for editing WL](https://user-images.githubusercontent.com/97796421/226695399-79580429-e80f-43f5-a351-1cf1bcf01e45.png)

**Comment by langdon0003** [comment]
@hnnam0906 edit Whitelist only for SINGLE mode by paste address to Input

**Comment by hnnam0906** [comment]
It is ok but we should make a note for user know to use it.

**Comment by langdon0003** [comment]
Please review 
@phoebehoang85 Should we update detail guide on git book for "edit whitelist" action?

**Comment by phoebehoang85** [comment]
Trong gitbook đã có hướng dẫn update whitelist rồi nhé. Close case
