### ISSUE TITLE
Internal: Report NFT: có cần kí wallet không? Không thấy gửi email báo report

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#239]
Report NFT có cần kí wallet không? Hiện tại bắt user kí wallet. Gas 0 đồng.

Không thấy gửi nội dung report về email --> các report gửi về email support@artzero.io

Thêm các trường contact của người report để liên hệ sau: email / telegram / discord, trường Email là trường bắt buộc

![image](https://user-images.githubusercontent.com/107900832/226698432-efbcea27-9587-4bcf-b744-770dd7969930.png)

**Comment by thienvip107** [comment]
report này chỉ gửi lên telegram thôi ạ

**Comment by phoebehoang85** [comment]
OK mình quay lại issue này sau. Close case
