### ISSUE TITLE
Internal: Create NFT: có vẻ không fetch được ảnh ổn định?

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#241]
Create NFT nhưng lúc hiện ảnh ngay, lúc chờ mãi không thấy ảnh. Như cái này chờ 5 phút, refresh rồi nhưng mãi k thấy.

Nếu vào từ Marketplace \ Collection \ ấn vào NFT chưa fetch ảnh này thì bị lỗi

![image](https://user-images.githubusercontent.com/107900832/226701115-408fd892-5893-476f-a29b-0774f18442d2.png)

Lỗi khi ấn vào NFT đó:

![image](https://user-images.githubusercontent.com/107900832/226702126-3c406bff-9bd6-4347-a876-da210caafe8b.png)

Nếu có 3 NFT rồi, up thêm cái thứ 4, sau khi up thành công chạy ra như sau (fetch ảnh NFT số 2 giống số 1). 4 NFT này đều có images khác nhau.

![image](https://user-images.githubusercontent.com/107900832/226703121-c4df5d2a-eb01-4e79-9d79-c19b5f5746e2.png)

Refresh lại thì ra như sau (NFT số 2 trở lại mất ảnh)

![image](https://user-images.githubusercontent.com/107900832/226703330-5c406a2b-570e-41da-915c-31b550a5840c.png)

Nếu list NFT 1, NFT đó bị chuyển sang tab LISTED, bên tab UNLISTED NFT số 2 bị fetch ảnh của NFT 1

![image](https://user-images.githubusercontent.com/107900832/226710708-66608094-feda-4e8b-9a0c-e4480c814836.png)

![image](https://user-images.githubusercontent.com/107900832/226710903-b98e7918-b675-4704-8bd6-d962cf718774.png)

**Comment by thienvip107** [comment]
chị tạo collection với nft mới ạ, cái này do collection cũ nên tạo nft mới get hash ko dc ạ

**Comment by phoebehoang85** [comment]
Reviewed & close case.
