### ISSUE TITLE
Internal:  Owner view NFT từ My NFTs và từ Marketplace khác nhau, nên điều chỉnh lại giống nhau

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#242]
Owner view NFT từ My NFTs và từ Marketplace khác nhau, nên điều chỉnh lại giống nhau. Thêm Tab Owner History và TX History nếu view từ My NFTs.

View từ My NFTs:
![image](https://user-images.githubusercontent.com/107900832/226705125-3e6770b8-27aa-4360-a35b-244f020ae97b.png)

View từ Marketplace:
![image](https://user-images.githubusercontent.com/107900832/226705516-c0ddb1e5-87c4-40cb-80e0-053bf0c5e7d8.png)

**Comment by langdon0003** [comment]
@phoebehoang85 chị lấy lại theo mẫu trên hay dưới vậy chị?
@thienvip107

**Comment by langdon0003** [comment]
updated please check @phoebehoang85

**Comment by phoebehoang85** [comment]
Chị vẫn thấy thiếu 1 số cái: @langdon0003 @thienvip107 
- transaction history
- owner history
- share social

![image](https://user-images.githubusercontent.com/107900832/227923215-04d19c63-1602-44cf-acaa-4d6c9e1d3e18.png)

**Comment by langdon0003** [comment]
Please check @phoebehoang85
