### ISSUE TITLE
Internal: Claim unsuccessful bids: không chạy ra trang sign wallet

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#244]
Claim unsuccessful bids: không chạy ra trang sign wallet, toast lên như vậy là thôi.

![image](https://user-images.githubusercontent.com/107900832/226731199-b7bf7a32-f30d-4b06-8684-ee3c2687ad8b.png)

**Comment by langdon0003** [comment]
please review
 @phoebehoang85

**Comment by phoebehoang85** [comment]
Reviewed & close case.
