### ISSUE TITLE
(Mobile) Cant share on Telegram properly error pop up

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#245]
![image](https://user-images.githubusercontent.com/117429099/226794148-56834a8f-4e5e-4c01-9487-8fee2b63f571.jpeg)

![image](https://user-images.githubusercontent.com/117429099/226794186-e77a1324-4fdc-485b-a5c6-543b87a263b7.jpeg)

**Comment by thienvip107** [comment]
lỗi do browser của subwallet

**Comment by mitchdoan** [comment]
a đã test lại và thấy ok rồi, em có thể close @thienvip107
