### ISSUE TITLE
Internal: Add admin role, phân quyền thêm Whitelist management

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#258]
Add admin role, phân quyền thêm Whitelist management

Ngoài ra  bỏ owner admin ra khỏi list whitelist management hoặc có bỏ vào nhưng không cho remove role. Vì remove role xong vẫn có thể toàn quyền làm tất cả các chức năng.

![image](https://user-images.githubusercontent.com/107900832/227789153-5d68cb7f-bc29-4b1c-bc99-fa918f27e68d.png)

![Uploading image.png…]()

**Comment by langdon0003** [comment]
Disable remove ADmin role of owner.
![image](https://user-images.githubusercontent.com/35419213/228081221-b1c35d57-34e3-4782-8880-7cc957a5c52a.png)

**Comment by langdon0003** [comment]
Please review @phoebehoang85
