### ISSUE TITLE
Internal: Withdraw history sai thông tin

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#259]
Withdraw history sai thông tin + sửa lại bảng + kiểm tra lại xem nếu owner có nhiều project thì withdraw ở project nào cũng được hay project nào withdraw project đó (history của project nào thì nằm ở đó)

Sai thông tin (project mới lập chưa có ai mint nhưng có số liệu ở đâu ra

![image](https://user-images.githubusercontent.com/107900832/227789681-af42d1fc-9c7a-4b26-88b8-8cabd983d15f.png)

sửa lại bảng như sau: làm rõ tiền vào (IN - tức là tiền được mint có revenue trả về), và (OUT - tiền withdraw các lần trước), Total balance tổng kết ở phía trên cùng.

![image](https://user-images.githubusercontent.com/107900832/227790293-5a317056-b609-4593-8f1c-d7d379468ab1.png)

**Comment by langdon0003** [comment]
Thien fixed please review
@phoebehoang85
