### ISSUE TITLE
Internal: Thời gian 12:00AM bị nhầm nên phase 2 chạy trước phase 1

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#260]
Thời gian bị nhầm:
12:00AM ngày 26/3 = 00 giờ sáng ngày 26/3 xảy ra trước 11:30 ngày 26/3
12:00PM ngày 26/3 = 12 giờ trưa ngày 26/3

Nên phase 2 chạy trước phase 1

![image](https://user-images.githubusercontent.com/107900832/227790861-2f663694-3e7b-456d-9a41-f852f0025a0c.png)

![image](https://user-images.githubusercontent.com/107900832/227790957-c88f9818-3788-4a41-8120-f1d9bb56816c.png)

Project phase:
![image](https://user-images.githubusercontent.com/107900832/227790896-ff788562-4193-4fd0-b79f-0329585f6a25.png)

Các phase:

![image](https://user-images.githubusercontent.com/107900832/227790931-a55b6f69-baf1-4866-859b-43e573d9f050.png)

**Comment by vup2p** [comment]
sau khi fix, ở bản git 37a392acafb7429af33dcf10a6642a8b3722fd96 xuất hiện lỗi invalid date trong offers bid
![image](https://user-images.githubusercontent.com/102939807/228055067-8a920fe2-42fb-4a31-9389-a3f6b84e2b7a.png)

**Comment by langdon0003** [comment]
please review @phoebehoang85 @vup2p
