### ISSUE TITLE
Internal: clear whitelist: clear 0.7 cho 10 whitelist chắc là số sai

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#262]
clear whitelist: clear 0.7 cho 10 whitelist chắc là số sai
Vì add 125 whitelist mất 0.9A thôi.

![image](https://user-images.githubusercontent.com/107900832/227793682-67c8d2d6-94b1-4518-9a99-4f1589b9b633.png)

**Comment by langdon0003** [comment]
please review @phoebehoang85

**Comment by langdon0003** [comment]
please review 
@phoebehoang85

**Comment by phoebehoang85** [comment]
Test lại, mình có clear được wl cho tất cả vào 1 lúc không, vì nếu cứ clear 10 cái một lần như này không biết khi nào mới xong.

Ngoài ra trước khi clear và sau khi clear không thấy có thay đổi gì nên user rơi vào tình trạng không biết làm động tác này làm gì, tới bao giờ thì hết @langdon0003 

![image](https://github.com/ArtZero-io/frontend-react/assets/107900832/9d8fa781-b28b-4d7a-a5f2-a9cce8425ac4)
