### ISSUE TITLE
No need to connect wallet to view offers and history

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#265]
## Describe the bug
Don't show offers and history when don't connect wallet

## To Reproduce
1. Go to [Homepage/#/marketplace](https://alephzero.artzero.io/#/marketplace)
2. Select NFT have offers

## Expected behavior
Show all offers and history

## Priority
What is the impact of this bug on the user, how critical is to fix? 

## Screenshots/Video
![image](https://user-images.githubusercontent.com/102939807/228056910-ef37c63e-5d49-45ac-8adb-d76cae08b924.png)

**Comment by langdon0003** [comment]
Please review @vup2p
