### ISSUE TITLE
Error cant push for sale is not clear

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#267]
![image](https://user-images.githubusercontent.com/117429099/228195024-4b8e18fa-4db3-4d6f-9cc5-90e15a7b9fe6.jpeg)

**Comment by thienvip107** [comment]
anh thử test lại xem ạ, em test trên máy em vẫn push on sale bình thường ạ

**Comment by mitchdoan** [comment]
anh thử nft khác a có cũng ko dc đây em

![image](https://user-images.githubusercontent.com/117429099/228412247-9c1a2a4e-4f25-4155-94c1-90657103b519.jpeg)

**Comment by thienvip107** [comment]
anh thử f5 lại browser xem dc ko ạ

**Comment by mitchdoan** [comment]
anh test bản mobile mà, em check dt xem có dc ko, mà em thử nft mà em tự tạo collection tự create nft ý

**Comment by thienvip107** [comment]
em test bản mobile trên subwallet được
 ấy ạ, ý em là f5 lại cái browser trên subwallet ấy ạ

**Comment by mitchdoan** [comment]
anh thử vẫn bị

**Comment by thienvip107** [comment]
![photo_2023-03-29_13-50-53](https://user-images.githubusercontent.com/42136863/228449928-48688a7c-0522-4952-9f04-9446e14e00ec.jpg)
Em test đây ạ, anh thử logout rra login lại ạ

**Comment by mitchdoan** [comment]
a làm lại kiểu gì vẫn there is some error

**Comment by mitchdoan** [comment]
cái này fixed chưa e nhỉ @langdon0003

**Comment by langdon0003** [comment]
I ve try on mainnet and it worked. 

Please try again If it's still pending please give more detail on context.
- Collection name & address
- NFT number
@mitchdoan
