### ISSUE TITLE
(Mobile) Cant connect to Nova, Polkadot

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#275]
when using subwallet app to access a0.artzero.io

https://user-images.githubusercontent.com/117429099/229099463-b9400172-e247-42ea-beba-6872e1197666.MOV

**Comment by langdon0003** [comment]
Fixed at commit [6b9bbd5e250dd05badc06fe2474971693b96f817](https://github.com/ArtZero-io/frontend-react/commit/6b9bbd5e250dd05badc06fe2474971693b96f817) please review @mitchdoan
