### ISSUE TITLE
Not enough balance msg didnt disappear

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#279]
![image](https://user-images.githubusercontent.com/117429099/229286507-186c963d-d878-4917-8f96-596d5aba8b05.png)

**Comment by langdon0003** [comment]
Need more context details. @mitchdoan 
It's work fine when I try to reproduce error. 

https://user-images.githubusercontent.com/35419213/229382357-f468be88-28c5-4694-a58f-e33d960ca1e5.mov

**Comment by mitchdoan** [comment]
yeah it is on and off, sometimes the error stuck there
