### ISSUE TITLE
Trait show 0%

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#281]
for 0.xx% should show 2 decimal to know how many items it has in the collection![image](https://user-images.githubusercontent.com/117429099/229297867-4ea5d9de-3e72-4f77-8a20-f3484a6e9e50.jpeg)

**Comment by langdon0003** [comment]
Fix 2 deciaml added.
Traits name come from Metadata json
![image](https://user-images.githubusercontent.com/35419213/229381962-329f3a9a-c05a-49cc-958f-ee2b2618441f.png)

**Comment by mitchdoan** [comment]
In the Filtering it is still showing 0%

**Comment by langdon0003** [comment]
Fixed Please review @mitchdoan
