### ISSUE TITLE
Sorting is not cached, every time need to resort Low to High again

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#282]
https://user-images.githubusercontent.com/117429099/229322893-952ec9eb-965f-4c0b-8bad-23d4bb8e2435.MOV

và đang ở page nào đấy thì bị quay lại page đầu

**Comment by langdon0003** [comment]
Update please review @mitchdoan

**Comment by langdon0003** [comment]
- [ ] Add save page state

**Comment by langdon0003** [comment]
Transform to Infinite loading for Marketplace.
