### ISSUE TITLE
Launchpad/Collection thumb nail sharing not working

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#285]
![image](https://user-images.githubusercontent.com/117429099/229340180-97081f9a-f2ae-4c82-96e6-7391769a3453.jpeg)

**Comment by langdon0003** [comment]
Thiện updated. please review @mitchdoan @phoebehoang85

**Comment by langdon0003** [comment]
@thienvip107 @vup2p 
Please inform @mitchdoan and @phoebehoang85 when done check & implement on main-net

**Comment by vup2p** [comment]
wait for deploy
