### ISSUE TITLE
Cant see all description in NFT modal

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#287]
![Screen Shot 2023-04-03 at 9 16 11 AM](https://user-images.githubusercontent.com/88643486/229396654-dff2c74c-d15e-46a3-b355-fbff01d73c7c.png)

**Comment by langdon0003** [comment]
Add hover show full text.

**Comment by langdon0003** [comment]
Please review 
@nad128668 @mitchdoan

**Comment by phoebehoang85** [comment]
Check ok, close case
