### ISSUE TITLE
Marketplace Page to add 4 random collections + show 20 all Collections

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#289]
Show 4 random collections between featured collections and all collections

**Comment by nad128668** [comment]
Following list:
- featured collections
- 4 random collections
- 10 trending collections (xếp theo volume)
- 10 new collections (xếp theo tgian)

**Comment by langdon0003** [comment]
Updated, Please review @nad128668 @mitchdoan

**Comment by langdon0003** [comment]
Updated, Please review 
@nad128668 @mitchdoan
