### ISSUE TITLE
Stats Page show 20 top collection by Volume

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#292]
instead of 5 as now

**Comment by langdon0003** [comment]
Updated

**Comment by langdon0003** [comment]
Updated please review 
@nad128668 @mitchdoan

**Comment by phoebehoang85** [comment]
Ok. close case.

![image](https://github.com/ArtZero-io/frontend-react/assets/107900832/a3bb864b-7115-4c4c-8bf1-632032984344)
