### ISSUE TITLE
traits percentage still not having 2 decimals in filter

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#299]
![image](https://user-images.githubusercontent.com/117429099/229475130-a7db0580-4b09-4a00-9881-91b9a0462117.png)

**Comment by langdon0003** [comment]
Updated

**Comment by mitchdoan** [comment]
![image](https://user-images.githubusercontent.com/117429099/229804378-dc09c3bd-26f8-44bf-a251-ce0e131720c4.png)

fixed can close it bro @langdon0003
