### ISSUE TITLE
Push for Sale enabled although collection is not on the marketplace yet

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#300]
![image](https://user-images.githubusercontent.com/117429099/229483311-d9772fde-b7b7-4313-a287-ce9825e7bce8.png)

and text should be This collection is not enabled on the Marketplace yet.

instead of Inactive

**Comment by langdon0003** [comment]
updated please review @phoebehoang85  @mitchdoan

**Comment by mitchdoan** [comment]
still show as in active @langdon0003

**Comment by langdon0003** [comment]
The text on hover "Inactive" is updated only.
You mean we should we change "Inactive"
![image](https://user-images.githubusercontent.com/35419213/233969548-02af6d0c-b829-44c0-a9f6-287cce6232e5.png)

to this
![image](https://user-images.githubusercontent.com/35419213/233969688-f9f71a92-2433-40f3-9e4d-d197d516b8d5.png)

@mitchdoan
