### ISSUE TITLE
description owner mint

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#301]
@tian_ng Cái này phải viết lại ở description là:
Project owner can mint remaining NFTs when phase is inactive or when project is ended.

![image](https://user-images.githubusercontent.com/117429099/229484530-c05e16d1-1865-4f9a-9032-8eac2c771d38.jpeg)

**Comment by langdon0003** [comment]
updated please review @phoebehoang85  @mitchdoan

**Comment by mitchdoan** [comment]
@nad010286 mày là owner thử test giúp xem lỗi này đã fix dc chưa nhé
