### ISSUE TITLE
(UX) Filter cant unselect -> suggest to click one more time to unselect

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#303]
![image](https://user-images.githubusercontent.com/117429099/229520619-bd92b347-1ca5-4d3c-aa18-2ab674fc33f8.jpeg)

**Comment by langdon0003** [comment]
Please review @mitchdoan

**Comment by mitchdoan** [comment]
it is not fixed yet![image](https://user-images.githubusercontent.com/117429099/231923679-dd9cd066-279d-4bfc-a413-9690781b4d54.png)

@langdon0003

**Comment by langdon0003** [comment]
Updated. Please check again. @mitchdoan

**Comment by langdon0003** [comment]
Please review. Both work on Desktop and Mobile so far.
@mitchdoan
