### ISSUE TITLE
4 PMP doesnt have body or calculation wrong? displaying 99.96%

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#305]
sao body mà 99.96% này, có 4 con k có body :)) khả năng mình ve? Hay là Predator và Predators
 @langdon0003 
![image](https://user-images.githubusercontent.com/117429099/229623365-be0a8e11-c200-44dc-ab14-03d1e0b5c968.jpeg)

**Comment by langdon0003** [comment]
fixed. please review @mitchdoan 
![image](https://user-images.githubusercontent.com/35419213/229682445-eebae98f-4308-4c12-bce2-8521c54a9b04.png)

**Comment by mitchdoan** [comment]
reviewed by @phoebehoang85 and it is fixed can be closed @langdon0003
