### ISSUE TITLE
Mainnet: Azero Boys xoá phase 1, nhưng whitelist vẫn còn phase 1

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#308]
Mainnet: Azero Boys: https://a0.artzero.io/#/launchpad/5FUw2p165KPH1cDWdZXv2bChqrqkQvXwDXs8N4EywkAGBgNj

xoá phase 1 , chỉ còn 1 phase, nhưng khi add whitelist vẫn còn 2 phase

Tổng supply 3333, phase 2 có 3297 nhưng k add được whitelist cho đủ 3333

![telegram-cloud-photo-size-4-5868751460987157202-y](https://user-images.githubusercontent.com/107900832/230290001-fb54262b-2b68-48d2-b027-86be5f070a93.jpg)

![telegram-cloud-photo-size-4-5868751460987157204-y](https://user-images.githubusercontent.com/107900832/230290113-4fef2eee-c884-4ce7-b74e-19e142705d11.jpg)

![telegram-cloud-photo-size-4-5868751460987157203-y](https://user-images.githubusercontent.com/107900832/230290245-62bb1b44-1e7d-4e6a-8a76-3cff0b02007e.jpg)

**Comment by langdon0003** [comment]
Updated. Please review @phoebehoang85

**Comment by langdon0003** [comment]
Please review 
@phoebehoang85

**Comment by phoebehoang85** [comment]
Close case.
