### ISSUE TITLE
1st Phase start & project start time không giống nhau

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#309]
Trên Testnet thời gian bắt đầu project đang bị sai. (như phía dưới)
Chắc nên thống nhất lại: thời gian của project & 1st phase phải trùng nhau. Không cho xoá phase 1 (nếu edit thì xoá các phase dưới nhưng riêng phase 1 không xoá được). Nếu đổi thời gian bắt đầu của phase 1 thì project time đổi luôn.
Như vậy trong ON-GOING & UPCOMING mới đúng.

https://a0-test.artzero.io/#/launchpad/5CGakVp8pwqB8zNwdgefgWWSiAUBw5k568Bu5LBk6YGugQRJ

Thằng này đặt giờ bắt đầu của project, còn phase 1 thì trong 6 ngày nữa:

![telegram-cloud-photo-size-4-5870605422275181738-y](https://user-images.githubusercontent.com/107900832/230340045-779e2a1b-7241-46a2-be84-1a9fa3ab016b.jpg)

Trong Upcoming giờ hiện lên là còn 1 ngày

![telegram-cloud-photo-size-4-5870605422275181737-y](https://user-images.githubusercontent.com/107900832/230340291-f8e39cea-8410-4b20-9b7a-bd51f2209636.jpg)

trên thanh countdown bên trong:

![image](https://user-images.githubusercontent.com/107900832/230341120-36c1ff21-6a9f-4f8f-aee9-24ce141d75fb.png)

**Comment by langdon0003** [comment]
Please review on Mainnet @phoebehoang85

**Comment by langdon0003** [comment]
Please review 
@phoebehoang85

**Comment by phoebehoang85** [comment]
Close case
