### ISSUE TITLE
LaunchPad view Project PMP should boost Visibility

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#310]
![image](https://user-images.githubusercontent.com/117429099/230523402-725a6bc8-b161-42dc-b99d-22c63fba799c.png)

create project visibility is much more than View project which need to be attend this time period

**Comment by langdon0003** [comment]
Updated. swap style of 2 button

![image](https://user-images.githubusercontent.com/35419213/233971118-9907c311-a111-44aa-ad2f-1de148872cfc.png)

Please review
@mitchdoan
