### ISSUE TITLE
Minting History close button should be inside the box

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#314]
ko tắt được Minting History do cái nút Close nó nằm ở trên. Cái này chắc ở nhiều modal đều gặp phải. @dragondaimyo @longpos Cần add git issue

![image](https://user-images.githubusercontent.com/117429099/230593045-867c8b23-c84d-428e-8ec7-9fb55695402a.jpeg)

**Comment by langdon0003** [comment]
Please review @mitchdoan
