### ISSUE TITLE
My Listings function

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#316]
Shen I'm on /account/nfts and select "my listing" (should be "listings") then take an action against a listing it takes me back to the "my collected" page rather than "my listing" where I was.  Would be nice to always end up where you started.

**Comment by langdon0003** [comment]
Please review @mitchdoan

**Comment by mitchdoan** [comment]
it is still going back to Collected after cancel sale, but this can be discussed @langdon0003

**Comment by langdon0003** [comment]
Page redirect after specific action is intentionally. please check action flow and suggest change detail. 
@mitchdoan

**Comment by mitchdoan** [comment]
not fixed for now

**Comment by langdon0003** [comment]
@mitchdoan  
please review again
