### ISSUE TITLE
Can not sell pending at Confirmation button

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#318]
Customer: Every time I try to sell I get this screen and it just stays blank no matter how long I sit there. Anyone else having that issue?![image](https://user-images.githubusercontent.com/117429099/230800013-e91a025d-7042-4385-b10d-65766f2a0750.jpeg]

**Comment by langdon0003** [comment]
Look like Nova wallet Issue.

**Comment by mitchdoan** [comment]
so cant do anything? @langdon0003
