### ISSUE TITLE
Activity Load more not working

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#331]
and too little entries per page![image](https://user-images.githubusercontent.com/117429099/231474724-7f55eb08-9f1c-4f33-9581-6ba6f4be2f36.jpeg)

**Comment by langdon0003** [comment]
- [x] Removed `load more` text
- [x] WIP _ Will add more item appear on list along fixing issue https://github.com/ArtZero-io/frontend-react/issues/322
#322

**Comment by langdon0003** [comment]
Updated. please check @mitchdoan

**Comment by mitchdoan** [comment]
its fixed, can be closed
