### ISSUE TITLE
Filter icon not visible enough

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#332]
![image](https://user-images.githubusercontent.com/117429099/231475179-320382ec-a851-4b93-ac4e-2f2a3f99d2ce.jpeg)

**Comment by langdon0003** [comment]
Updated. Plz review @mitchdoan 
![image](https://user-images.githubusercontent.com/35419213/231633995-b359dc73-f42f-492b-8758-0b632e6f2b19.png)

**Comment by mitchdoan** [comment]
em cho cái filter chiều ngang dài ra cái all bé lại đc ko @langdon0003
