### ISSUE TITLE
Traits percentage overlap

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#335]
![image](https://user-images.githubusercontent.com/117429099/231722159-ef1479f8-2e7e-4e19-8d3a-0af3535833db.jpeg)

Lỗi overlap cái % này add vào git issue nhé @dragondaimyo

**Comment by langdon0003** [comment]
Need more context and details.
Did you view with normal screen full size or split window to half of screen?
@nad010286 @mitchdoan

**Comment by mitchdoan** [comment]
using mobile

**Comment by langdon0003** [comment]
Fixed
