### ISSUE TITLE
Activity Creator address to move up to below Contract address

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#336]
and remove the creator address in the activity history database, it will make info display in activity less duplicated and more useful

![image](https://user-images.githubusercontent.com/117429099/231797164-00d550da-c607-4284-8b0e-32f664d2e8e6.jpeg)

**Comment by langdon0003** [comment]
Please review @mitchdoan

**Comment by mitchdoan** [comment]
it is fixed, can be closed
