### ISSUE TITLE
Astar update Project creation

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#337]
I agree to pay 4500 ASTR to ArtZero.io for the creation of new project. This fee is non-refundable. 

I agree to a 5% share of the mint price for every sucessful mint to be distributed to ArtZerio.io

I agree to ArtZero's Term of Service

-----22
I agree to a 5% share of the mint price for every sucessful mint to be distributed to ArtZerio.io
=> agree to a 5% hay agree to pay 5%
vậy a @nad010286

**Comment by langdon0003** [comment]
Done on a0 side @ commit [0672a5f2e943dee7e2046f3e8fe18e6355c7358b](https://github.com/ArtZero-io/frontend-react/commit/0672a5f2e943dee7e2046f3e8fe18e6355c7358b)

**Comment by mitchdoan** [comment]
fixed description has been changed
