### ISSUE TITLE
Project description should be able to separated in paragraph

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#338]
![image](https://user-images.githubusercontent.com/117429099/231921073-1f160c0d-b09f-47a8-b619-8eae0c955161.jpeg)

**Comment by langdon0003** [comment]
This area is designed with 150 characters only. 
Increase space it not solve this issue imo.
Need discuss with designer.

**Comment by langdon0003** [comment]
- [ ] Limit char to 250

**Comment by mitchdoan** [comment]
this is a workaround
