### ISSUE TITLE
[Launchpad] Mint History

### ISSUE THREAD

**Issue by nad128668** [ArtZero-io/frontend-react#340]
To show total Minted Amount and Search for address

**Comment by langdon0003** [comment]
- [x] Search address @thienvip107 fixed
- [x] Show total mint

**Comment by langdon0003** [comment]
@mitchdoan please review

**Comment by nad128668** [comment]
Total minted: chưa đúng

**Comment by langdon0003** [comment]
update at commit [6ec8b4f0bf893d2737cbb809eb82ea42fd98c187](https://github.com/ArtZero-io/backend/commit/6ec8b4f0bf893d2737cbb809eb82ea42fd98c187)
Fix total amount:
- /api/withdraw-event-schemas
- /api/launchpad-minting-event-schemas-v1
 [mainnet-1.0_pretest](https://github.com/ArtZero-io/backend/compare/mainnet-1.0_pretest)
