### ISSUE TITLE
Project has sold out move to Ended projects in Launchpad

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#344]
![image](https://user-images.githubusercontent.com/102939807/232387414-9eb52115-1a10-4d9c-b405-7760ab92a22a.png)

Project has sold out hide line Public mint
![image](https://user-images.githubusercontent.com/102939807/232387818-d2afefa2-a0fb-41e6-ab61-92bc6816e121.png)

**Comment by langdon0003** [comment]
Updated. Please check @vup2p

**Comment by vup2p** [comment]
need to improve UI, not show coutdown if project end
![image](https://user-images.githubusercontent.com/102939807/234529310-f8491cfa-525a-4eb9-af38-279159069516.png)
