### ISSUE TITLE
Blur the decimals to users see number easier

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#345]
![image](https://user-images.githubusercontent.com/117429099/232393988-f2657417-c270-43b0-9c4c-92269c8a3e02.jpeg)

**Comment by langdon0003** [comment]
Update for price of trade-related component. please review @mitchdoan 
![image](https://user-images.githubusercontent.com/35419213/233928038-9a428a7c-253f-46d0-845c-69cd4f5bd975.png)

**Comment by langdon0003** [comment]
Updated Text Color to b4b4b4 @vup2p
