### ISSUE TITLE
direct to marketplace if wrong collection address

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#347]
https://a0.artzero.io/collection/5E7HFbvv7o4zFpJxnUsJF5CNktew1T6nh3gctbkSTWGAei?is_for_sale=true
![image](https://user-images.githubusercontent.com/102939807/232614682-d0178b50-abab-49f8-9657-69086bc38475.png)
Expect 
display same as the Launchpad  if wrong collection address
https://a0.artzero.io/launchpad/5F4fBoxKBwXZ5fprZPtkhXtesR7PXEWny6KqwWEHbZWX

**Comment by langdon0003** [comment]
Done. please review @vup2p
