### ISSUE TITLE
User request: more stats

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#349]
It would be nice to know in advance the max supply of a NFT collection.
Also I'd like to see some statistic graphics

**Comment by langdon0003** [comment]
Currently we only have max supply of collection create via launchpad.

For Simple mode, It's depend and increase base on NFT owner upload & created.
For Advance mode. It's also depend and increase base on NFT owner upload & created. But we can update manual max supply for some Adv mode collection by contact collection owner.  

Need more details on "some statistic graphics", it's like chart?
@mitchdoan
