### ISSUE TITLE
% of minting % incorrect need 2 decimals

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#351]
![image](https://user-images.githubusercontent.com/117429099/232657846-1e378168-3c7c-438b-8862-1b73fbc269f9.jpeg)

**Comment by langdon0003** [comment]
Done. Please review @mitchdoan 
![image](https://user-images.githubusercontent.com/35419213/233886138-4194fd24-d3fc-46af-90ea-bd0715f58f98.png)
