### ISSUE TITLE
avoid displaying the same collection many times in the marketplace page

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#352]
![image](https://user-images.githubusercontent.com/102939807/232721250-7f0ed5d6-2843-448c-9c04-407ce6969d98.png)

**Comment by langdon0003** [comment]
Currently, we have a few collection with 4 section of collection show on Homepage as issue #289 (Marketplace Page to add 4 random collections + show 20 all Collections) that why high chance sometime collection will dup.
Do you have any suggestion? 
@vup2p

**Comment by langdon0003** [comment]
- [x] Remove random section 
- [ ] Refactor design; need discuss Ms Thao
