### ISSUE TITLE
My-bids doesnt have link and goes to launchpad instead

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#354]
link my bid shows

![image](https://user-images.githubusercontent.com/117429099/232725538-0950932f-3e5c-40af-85f6-a61de2d92299.jpeg)

nhưng copy address hoặc browse address này lại là https://a0.artzero.io/launchpad/5F4fBoxKBwXZ5fprZPtkhXtesR7PXEWny6KqwWEHbZWXkg55#/account/nfts

**Comment by mitchdoan** [comment]
have to use public account link and options use same link https://a0.artzero.io/account/nfts

**Comment by langdon0003** [comment]
- [x] add share button copy public account for user

**Comment by langdon0003** [comment]
@mitchdoan please review

**Comment by mitchdoan** [comment]
the issue is still there but wont fix and work around is to have account profile with details

**Comment by mitchdoan** [comment]
where is the button, i check pretest.artzero.io dont see it

**Comment by langdon0003** [comment]
@mitchdoan you can find it here

![image](https://github.com/ArtZero-io/frontend-react/assets/35419213/b3f5f1b7-b4e5-4891-8273-c2142a3cf1a3)
