### ISSUE TITLE
Bid Accepted activity to moved to Purchase

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#356]
since it is a buying/selling transaction and in fact it show buyer and seller info

![image](https://user-images.githubusercontent.com/117429099/232778242-0d6d7ae8-e66d-404a-9d0d-1c8d2739cad1.jpeg)

**Comment by langdon0003** [comment]
- [x] Merge to 1 table

**Comment by langdon0003** [comment]
Updated
