### ISSUE TITLE
Amount should be on the same line

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#357]
![image](https://user-images.githubusercontent.com/102939807/233009050-77cf879a-872c-487e-899f-6e6b28f284c5.png)

**Comment by langdon0003** [comment]
Chờ build

**Comment by langdon0003** [comment]
@vup2p please review

**Comment by vup2p** [comment]
![image](https://github.com/ArtZero-io/frontend-react/assets/102939807/6b4c2687-775e-4d65-803a-2412cfe7d875)

**Comment by langdon0003** [comment]
@vup2p plz review

![Screenshot 2023-05-22 090354](https://github.com/ArtZero-io/frontend-react/assets/35419213/9eeec2fb-3857-43c6-a14a-12231dab4afc)
