### ISSUE TITLE
User Request: function to Remove All Bids

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#358]
Team, when can we expect a REMOVE ALL bids button.. Right now I have to manually go through every AZPunk to remove my bids since the my bids page is not loading anymore

**Comment by langdon0003** [comment]
chờ build

**Comment by langdon0003** [comment]
@mitchdoan please review

**Comment by mitchdoan** [comment]
remove bids -> remove all bids a vẫn thấy display là remove bids

**Comment by langdon0003** [comment]
@mitchdoan 
pls check, update on pretest
![image](https://github.com/ArtZero-io/frontend-react/assets/35419213/0ccf6e06-6d16-46bf-bad8-9ec76962e703)

**Comment by mitchdoan** [comment]
nếu chỉ có 1 bid thì hiện là Remove Bid thôi dc ko em, hiện tại a có 1 mà nó cũng ghi remove all bids @langdon0003 

![image](https://github.com/ArtZero-io/frontend-react/assets/117429099/8b2ac61d-1a0b-4f53-8ef0-8a8d6967ca48)

**Comment by langdon0003** [comment]
@mitchdoan please review
