### ISSUE TITLE
in my bid, show duplicate collection

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#360]
![image](https://user-images.githubusercontent.com/102939807/234536489-50340b80-b252-4f4f-a501-869002300791.png)

**Comment by langdon0003** [comment]
Fix at commit [f073470693ed8166e288c8d96ce7a6bcebfba826](https://github.com/ArtZero-io/frontend-react/commit/f073470693ed8166e288c8d96ce7a6bcebfba826)

Please review @vup2p
