### ISSUE TITLE
User Request: Activity - timestamp add and remove Block

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#361]
You can also add a timestamp too in addition to block no.

@langdon0003

**Comment by langdon0003** [comment]
Update at commit [7bcdaf6290b3435caa5c0a4b1f5591ed8f969610](https://github.com/ArtZero-io/frontend-react/commit/7bcdaf6290b3435caa5c0a4b1f5591ed8f969610)
please review @mitchdoan
