### ISSUE TITLE
Add Popup to allow cookies

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#364]
![image](https://github.com/ArtZero-io/frontend-react/assets/117429099/1634ccf7-e6e3-4562-80c0-87d02174a30c)

vào https://trade.d5.xyz/trade 
xem ví dụ

mình cần add cho cả ArtZero lẫn Inkwhale

**Comment by mitchdoan** [comment]
anh chưa thấy hỏi gì cả ở web lẫn mobile

**Comment by langdon0003** [comment]
a check giúp e ở trang pretest nhe.
mà thông báo này nếu chọn ok đồng ý thì về sau ko hiện nữa đâu a.

@mitchdoan 

![image](https://github.com/ArtZero-io/frontend-react/assets/35419213/b1ab4fd9-33de-42f9-9407-fa84eb2b937e)

**Comment by mitchdoan** [comment]
giờ anh thấy rồi, customer click ok với click đóng thì có khác nhau ko

**Comment by mitchdoan** [comment]
@langdon0003
