### ISSUE TITLE
Normal listing but successful msg show bulk

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#368]
when listing a single item, msg show Bulk listing tx completed

it should be changed The listing is successful

**Comment by langdon0003** [comment]
Update as following table

| Current | Single |
|----------|----------|
| All NFTs have been approved successfully |  NFT have been approved successfully |
| Approval are not fully successful! xxx approvals completed successfully |  Approval is not successful! |
| Bulk listing on marketplace.. | Listing on marketplace..  |
| All NFTs have been listed successfully | NFT has been listed successfully |
| Bulk listings are not fully successful! xxx listings completed successfully. | The listings is not fully successful! |

**Comment by langdon0003** [comment]
@mitchdoan please review on pretest
