### ISSUE TITLE
Bulk transfer: choose 1 but it still call Bulk transfer

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#369]
![image](https://github.com/ArtZero-io/frontend-react/assets/117429099/20619b48-3301-4ff9-872c-d569f8687b63)

**Comment by langdon0003** [comment]
Your expect behavior's when have 1 item
- show icon but not allow click to show ?
- not show Icon bulk action (transfer/listing/cancel) ?
@mitchdoan

**Comment by mitchdoan** [comment]
chỉ cần thay từ bulk tranfer thành transfer là cũng ok em ạ @langdon0003
