### ISSUE TITLE
Reward date shouldnt be on Sunday

### ISSUE THREAD

**Issue by mitchdoan** [ArtZero-io/frontend-react#370]
Ngày lấy rewards đúng CN, chắc phải chỉnh lại các tháng để tránh CN ra @dragondaimyo @longpos add git issue cá i này nhé. Nếu là t07 CN thì m để từ thứ 6 luôn tới hết tháng

**Comment by phoebehoang85** [comment]
close case. review & report issue trong các tháng tiếp theo nếu xảy ra lỗi.
