### ISSUE TITLE
ENV test: sắp xếp Highest first - Lowest first nếu ở Tab All hoặc Unlist thì xếp theo alphabet

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#379]
sắp xếp Highest first - Lowest first nếu ở Tab All hoặc Unlist thì xếp theo alphabet, không phải highest hoặc lowest.

Trong tab Unlist vì không có giá nên có thể hiểu được.

Trong tab All thì có cả giá, nhưng đều xếp theo thứ tự abc

![image](https://github.com/ArtZero-io/frontend-react/assets/107900832/1e526ce5-c7c1-49fc-a69c-5e214e9f3004)

Liệu có nên làm:

- Tab All hoặc Unlist thì đổi thành A - Z order / Z - A order
- Tab Listed thì giữ nguyên Lowest first / Highest first

**Comment by langdon0003** [comment]
Fixed @phoebehoang85
