### ISSUE TITLE
ENV: share NFT sai link

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#381]
share NFT sai link

Share telegram: Link: https://alephzero.artzero.io/collection/5DmnLFVw6GKvvifSkC12eUsKwK7a5dj9pqyPYjUkU8BSjH5v?is_for_sale=false
(Mushroom #1)

lúc share ra thì link là: https://a0.artzero.io/nft/5DmnLFVw6GKvvifSkC12eUsKwK7a5dj9pqyPYjUkU8BSjH5v/1

Các phần share sang nền tảng khác cũng không chạy đúng

![image](https://github.com/ArtZero-io/frontend-react/assets/107900832/3610c4ac-82d3-4f21-835d-d378be5f9255)

**Comment by langdon0003** [comment]
Fixed. @phoebehoang85
