### ISSUE TITLE
Hide remove bid in public account page

### ISSUE THREAD

**Issue by vup2p** [ArtZero-io/frontend-react#383]
https://a0.artzero.io/public-account/nfts/5CXx9W4HpbDCcU3M7RST2KPM8K3yPogaG5jkvX7quy3LiRKN
![image](https://github.com/ArtZero-io/frontend-react/assets/102939807/8cb2742d-328e-4448-809a-ed6f4cb8b312)

**Comment by langdon0003** [comment]
Updated. @vup2p

**Comment by vup2p** [comment]
the first access, show error
![image](https://github.com/ArtZero-io/frontend-react/assets/102939807/5a39dfc0-dbfb-4029-a74d-46e0918fb96a)
