### ISSUE TITLE
Azero ID Mainnet: check lại display thời gian, conflict với Azero ID

### ISSUE THREAD

**Issue by phoebehoang85** [ArtZero-io/frontend-react#387]
ID này chị mua tối 22/8, thời gian registration & expire bị conflict với Azero ID, có vẻ hiển thị thời gian trên trang của mình bị sai

![image](https://github.com/ArtZero-io/frontend-react/assets/107900832/73fe2789-3ccc-4c44-a257-a7b76835fd42)

![image](https://github.com/ArtZero-io/frontend-react/assets/107900832/f67fa612-8b20-40f4-b4b4-f0e74a0eb4e4)

**Comment by langdon0003** [comment]
uppdated.
@phoebehoang85 please review
